POST http://localhost:8081/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InFAZ21haWwuY29tIiwiZXhwIjoxNzM5NjI3Mzg0LCJ1c2VySWQiOjR9.MkrO-0biy8Sb48MQNP2HGeFCFb-46CbR05rqdI_JLl8